### ISSUE TITLE
f2fs (Flash Friendly File System) Support

### ISSUE THREAD

**Issue by ashb** [hypriot/image-builder-raw#10]
As the title suggests: any plan to support f2fs, specifically for an rpi2 image?

From a cursory look: It looks like build an f2fs image here is easy but we might need a more recent version of guestfs than is in debian/ubuntu to support f2fs on guestfish.

**Comment by firecyberice** [comment]
Currently there are no plans to support it but feel free to provide a PR.
All howtos for fixing fs errors on RPIs are for EXT4. With this in mind another filesystem will make the use of our image more complicated.

**Comment by ashb** [comment]
Got it working and booting with very few changes needed (a change to mkfs in here, and some changes to fstab and cmdline.txt in image-builder-rpi), but ran into an issue: the f2fs-tools in ~16.04~ Jessie doesn't have a 'resize.f2fs' -- that command is only available in ~Zesty~ Debian Testing :/

**Comment by ashb** [comment]
Okay bigger problem: resize.f2fs (from testing) can't resize a mounted filesystem. I think that pretty much scuppers it for Hypriot images as they are built.

**Comment by ashb** [comment]
I don't have time or desire to do this as it's a bigger bit of work then first thought. I'll close this issue.
